import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useConfig } from '../../store/useConfig.js';
import { useWordStore } from '../../store/useWordStore.js';
import { useProgressStore } from '../../store/useProgressStore.js';
import { useUiStore } from '../../store/useUiStore.js';
import { parseText, getSentenceForToken } from '../../utils/parser.js';
import { explainWord } from '../../services/ai.js';
import { fetchYouTubeTranscript } from '../../services/youtube.js';
import { BookIcon, CheckCircleIcon, PlayIcon, ReloadIcon, SearchIcon, SparkIcon } from '../shared/icons.jsx';
import SpeakButton from '../shared/SpeakButton.jsx';
import { Badge } from '../ui/badge.jsx';

function estimateMinutes(tokens = []) {
  const wordCount = tokens.filter((token) => token.type !== 'space' && token.clean).length;
  return Math.max(1, Math.ceil(wordCount / 180));
}

function isValidYoutubeUrl(value) {
  try {
    const url = new URL(value);
    return url.hostname.includes('youtube.com') || url.hostname.includes('youtu.be');
  } catch {
    return false;
  }
}

export default function Reader({ onPractice }) {
  const { config } = useConfig();
  const { words, addWord, getWordByText, markSeenInReader, updateWord } = useWordStore();
  const { recordReaderWord } = useProgressStore();
  const { pushToast } = useUiStore();

  const [rawText, setRawText] = useState('');
  const [youtubeUrl, setYoutubeUrl] = useState('');
  const [youtubeStatus, setYoutubeStatus] = useState(null);
  const [tokens, setTokens] = useState(null);
  const [sessionWords, setSessionWords] = useState([]);
  const [tooltip, setTooltip] = useState(null);

  const tooltipRef = useRef(null);
  const textAreaRef = useRef(null);
  const youtubeInputRef = useRef(null);

  const bankWords = useMemo(() => new Set(words.map((word) => word.word)), [words]);
  const clickedWords = useMemo(() => new Set(sessionWords.map((word) => word.wordText)), [sessionWords]);
  const estimatedSessionMinutes = useMemo(() => estimateMinutes(tokens || []), [tokens]);

  const focusEntry = useCallback(() => {
    if (rawText.trim()) {
      textAreaRef.current?.focus();
      return;
    }
    if (youtubeUrl.trim()) {
      youtubeInputRef.current?.focus();
      return;
    }
    textAreaRef.current?.focus();
  }, [rawText, youtubeUrl]);

  const startReading = useCallback(() => {
    if (!rawText.trim()) {
      pushToast({
        kind: 'warning',
        source: 'reader',
        title: 'Texto vazio',
        description: 'Cole um texto ou importe uma legenda antes de iniciar.',
      });
      focusEntry();
      return;
    }

    const parsedTokens = parseText(rawText.trim());
    setTokens(parsedTokens);
    setSessionWords([]);
    setTooltip(null);
    setYoutubeStatus(null);
  }, [focusEntry, pushToast, rawText]);

  const handleYouTubeImport = useCallback(async () => {
    if (!youtubeUrl.trim()) {
      pushToast({
        kind: 'warning',
        source: 'reader',
        title: 'URL vazia',
        description: 'Cole uma URL valida do YouTube para importar a legenda.',
      });
      youtubeInputRef.current?.focus();
      return;
    }

    if (!isValidYoutubeUrl(youtubeUrl.trim())) {
      const nextStatus = {
        state: 'error',
        message: 'URL invalida. Use um link do YouTube completo.',
      };
      setYoutubeStatus(nextStatus);
      pushToast({
        kind: 'error',
        source: 'reader',
        title: 'URL invalida',
        description: nextStatus.message,
      });
      youtubeInputRef.current?.focus();
      return;
    }

    setYoutubeStatus({ state: 'loading', message: 'Buscando legenda em ingles...' });

    try {
      const result = await fetchYouTubeTranscript(youtubeUrl.trim());
      setRawText(result.text);
      const nextStatus = {
        state: 'success',
        message: `Legenda carregada (${result.language}${result.isAutoGenerated ? ' auto' : ''}).`,
      };
      setYoutubeStatus(nextStatus);
      pushToast({
        kind: 'success',
        source: 'reader',
        title: 'Legenda importada',
        description: nextStatus.message,
      });
      textAreaRef.current?.focus();
    } catch (error) {
      const nextStatus = {
        state: 'error',
        message: error.message || 'Nao foi possivel carregar a legenda.',
      };
      setYoutubeStatus(nextStatus);
      pushToast({
        kind: 'error',
        source: 'reader',
        title: 'Importacao falhou',
        description: nextStatus.message,
      });
    }
  }, [pushToast, youtubeUrl]);

  const handleWordClick = useCallback(async (tokenIdx, token) => {
    if (!token.clean) return;

    const existing = getWordByText(token.clean);
    const sentence = getSentenceForToken(tokens, tokenIdx);

    // Apenas abre o tooltip — não salva nada ainda
    setTooltip({
      tokenIdx,
      word: token.raw,
      clean: token.clean,
      loading: true,
      text: '',
      exist: Boolean(existing),
      existingId: existing?.id || null,
      sentence,
    });

    try {
      const aiConfig = config.provider ? config : null;
      const result = await explainWord({
        word: token.raw,
        sentence,
        userLevel: config.userLevel || 'B1',
        config: aiConfig,
      });

      setTooltip((current) => current?.tokenIdx === tokenIdx
        ? { ...current, loading: false, text: result.text, fromAI: result.fromAI }
        : current);
    } catch (error) {
      setTooltip((current) => current?.tokenIdx === tokenIdx
        ? { ...current, loading: false, text: `Erro: ${error.message}` }
        : current);
    }
  }, [config, getWordByText, tokens]);

  const closeTooltip = useCallback((event) => {
    if (tooltipRef.current && !tooltipRef.current.contains(event.target)) {
      setTooltip(null);
    }
  }, []);

  const addToBank = useCallback(() => {
    if (!tooltip) return;

    const existing = getWordByText(tooltip.clean);
    let wordId = existing?.id;

    if (!existing) {
      const added = addWord(tooltip.clean, {
        originalSentence: tooltip.sentence,
        tag: 'contexto',
        initialStatus: 'reconhecida',
      });
      wordId = added?.id;

      // Sentence mining: auto-create contextual flashcard from original sentence
      if (wordId && tooltip.sentence) {
        import('../../store/useCardStore.js').then(({ useCardStore }) => {
          useCardStore.getState().addContextualFlashcard({
            wordId,
            wordText: tooltip.clean,
            originalSentence: tooltip.sentence,
            config,
          });
        });
      }
    }

    if (wordId && !sessionWords.find((sw) => sw.wordId === wordId)) {
      setSessionWords((current) => [
        ...current,
        { wordId, wordText: tooltip.clean, originalSentence: tooltip.sentence },
      ]);
      recordReaderWord({ wordId, isNewWord: !existing, isRecycled: Boolean(existing) });
      pushToast({
        kind: 'success',
        source: 'reader',
        title: 'Palavra capturada',
        description: `"${tooltip.clean}" adicionada às capturas.`,
      });
    }

    if (existing && wordId) {
      markSeenInReader(wordId);
      updateWord(wordId, { lastSeenAt: Date.now() });
    }

    setTooltip(null);
  }, [addWord, getWordByText, markSeenInReader, pushToast, recordReaderWord, sessionWords, tooltip, updateWord]);

  const reset = useCallback(() => {
    setTokens(null);
    setRawText('');
    setSessionWords([]);
    setTooltip(null);
    setYoutubeStatus(null);
  }, []);

  useEffect(() => {
    const handlePageAction = (event) => {
      const action = event.detail?.action;
      if (action !== 'reader-primary') return;

      if (tokens === null) {
        if (rawText.trim()) {
          startReading();
          return;
        }
        focusEntry();
        return;
      }

      if (sessionWords.length > 0 && onPractice) {
        onPractice(sessionWords);
        return;
      }

      pushToast({
        kind: 'info',
        source: 'reader',
        title: 'Sessao pronta para captura',
        description: 'Clique em palavras do texto para montar a pratica desta sessao.',
      });
    };

    window.addEventListener('langflow:page-action', handlePageAction);
    return () => window.removeEventListener('langflow:page-action', handlePageAction);
  }, [focusEntry, onPractice, pushToast, rawText, sessionWords, startReading, tokens]);

  return (
    <div className="text-neutral-800 antialiased min-h-screen flex flex-col pt-0 lg:pt-0 pb-16" onClick={closeTooltip}>
      <main className="w-full mt-2 lg:mt-4">
        {tokens === null ? (
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">

            {/* YouTube Entry Card */}
            <div className="bg-white rounded-xl p-6 md:p-8 shadow-[0_1px_3px_rgba(20,20,19,0.06)] border border-neutral-200/70 flex flex-col relative overflow-hidden">
              <div className="absolute top-0 right-0 w-64 h-64 bg-[#eef0ec] rounded-full blur-3xl -translate-y-1/2 translate-x-1/3 opacity-70"></div>

              <div className="relative z-10">
                <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-neutral-100 border border-neutral-200 mb-6 w-max">
                  <span className="w-2 h-2 rounded-full bg-[#647568]"></span>
                  <span className="text-[10px] font-bold text-neutral-500 uppercase tracking-[0.12em]">Entrada rápida</span>
                </div>

                <h3 className="text-lg font-semibold font-heading text-neutral-900 mb-2">Comece por um vídeo do YouTube</h3>
                <p className="text-sm text-neutral-500 leading-relaxed mb-8 max-w-sm">Use uma legenda real para trazer contexto natural antes de praticar.</p>

                <div className="mt-4 space-y-3">
                  <label className="text-[10px] font-bold text-neutral-400 uppercase tracking-[0.12em]">URL do vídeo</label>
                  <div className="flex flex-col sm:flex-row gap-3">
                    <div className="relative flex-1 group">
                      <SearchIcon className="absolute left-4 top-1/2 -translate-y-1/2 h-4 w-4 text-neutral-400 group-focus-within:text-[#35403A] transition-colors" />
                      <input
                        ref={youtubeInputRef}
                        className="w-full pl-11 pr-4 py-3 bg-neutral-50 hover:bg-neutral-100/70 focus:bg-white border border-neutral-200 focus:border-[#647568] focus:ring-2 focus:ring-[#35403A]/15 rounded-xl shadow-[0_1px_2px_rgba(20,20,19,0.04)] text-sm transition-all outline-none placeholder-neutral-400"
                        type="url"
                        placeholder="https://www.youtube.com/watch?v=..."
                        value={youtubeUrl}
                        onChange={(event) => setYoutubeUrl(event.target.value)}
                      />
                    </div>
                    <button
                      className="bg-[#35403A] hover:bg-[#232625] text-white px-6 py-2.5 rounded-full font-semibold text-sm transition-colors flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed whitespace-nowrap"
                      onClick={handleYouTubeImport}
                      disabled={!youtubeUrl.trim() || youtubeStatus?.state === 'loading'}
                    >
                      {youtubeStatus?.state === 'loading' ? <SparkIcon size={16} className="animate-spin text-[#647568]" /> : <PlayIcon size={16} />}
                      {youtubeStatus?.state === 'loading' ? 'Importando...' : 'Importar'}
                    </button>
                  </div>
                </div>

                {youtubeStatus ? (
                  <div className={`mt-5 p-3 rounded-xl text-sm font-medium flex items-center gap-2 ${youtubeStatus.state === 'success' ? 'bg-green-50 text-green-700 border border-green-200' : youtubeStatus.state === 'error' ? 'bg-[#eef0ec] text-[#35403A] border border-[#CED1C6]' : 'bg-[#eef0ec] text-[#35403A] border border-[#CED1C6]'}`}>
                    {youtubeStatus.message}
                  </div>
                ) : (
                  <div className="mt-5 text-sm text-neutral-500 leading-relaxed">Se a legenda não existir, cole o texto manualmente ao lado.</div>
                )}
              </div>
            </div>

            {/* Text Entry Card */}
            <div className="bg-primary rounded-xl p-6 md:p-8 shadow-[0_1px_3px_rgba(20,20,19,0.06)] border border-neutral-200/70 flex flex-col relative overflow-hidden text-white min-h-[450px]">
              <div className="absolute bottom-0 right-0 w-64 h-64 bg-white/10 rounded-full blur-3xl translate-y-1/3 translate-x-1/3"></div>

              <div className="relative z-10 flex flex-col h-full">
                <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/20 border border-white/10 mb-6 w-max">
                  <span className="w-2 h-2 rounded-full bg-white animate-pulse"></span>
                  <span className="text-[10px] font-bold text-white/90 uppercase tracking-[0.12em]">Sessão de leitura</span>
                </div>

                <h3 className="text-lg font-semibold font-heading text-white mb-2">Cole seu texto em inglês</h3>
                <p className="text-white/70 mb-6 max-w-md">Reader, tooltip contextual e prática seguem o mesmo fluxo.</p>

                <div className="flex-1 flex flex-col">
                  <label className="text-[10px] font-bold text-white/60 uppercase tracking-[0.12em] mb-2">Texto da sessão</label>
                  <textarea
                    ref={textAreaRef}
                    className="w-full flex-1 min-h-[160px] p-4 bg-white/10 border border-white/20 hover:bg-white/15 focus:bg-white/20 focus:border-white/40 rounded-xl text-sm transition-all outline-none placeholder-white/40 text-white resize-none"
                    style={{ fontSize: 16, lineHeight: 1.7 }}
                    placeholder={'Exemplo: artigo, roteiro ou legenda...'}
                    value={rawText}
                    onChange={(event) => setRawText(event.target.value)}
                  />
                </div>

                <div className="mt-6 flex flex-col sm:flex-row items-center justify-between gap-4">
                  <span className="text-sm font-bold text-white/60 bg-white/10 px-4 py-1.5 rounded-full border border-white/10">
                    {rawText.trim().split(/\s+/).filter(Boolean).length} palavras
                  </span>
                  <button
                    className="bg-white text-[#232625] hover:bg-neutral-50 px-6 py-2.5 rounded-full font-semibold text-sm transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2 w-full sm:w-auto"
                    onClick={startReading}
                    disabled={!rawText.trim()}
                  >
                    <SearchIcon size={18} />
                    Iniciar leitura
                  </button>
                </div>

                {!config.provider && (
                  <div className="mt-4 p-3 bg-[#647568]/20 text-[#CED1C6] border border-[#647568]/30 rounded-xl text-xs font-semibold">
                    Nenhuma IA configurada. Fallback local ativo.
                  </div>
                )}
              </div>
            </div>

          </div>
        ) : (
          <div className="flex flex-col gap-6">

            {/* Workspace Header / Session Bar */}
            <div className="bg-white rounded-xl p-6 md:p-8 shadow-[0_1px_3px_rgba(20,20,19,0.06)] border border-neutral-200/70 flex flex-col md:flex-row items-center justify-between gap-4">
              <div className="flex items-center gap-6">
                <div className="flex items-center gap-3">
                  <div className="w-12 h-12 bg-[#eef0ec] rounded-2xl flex items-center justify-center text-[#35403A] border border-[#CED1C6]/50">
                    <BookIcon size={20} />
                  </div>
                  <div>
                    <p className="text-[10px] font-bold text-neutral-400 uppercase tracking-[0.12em]">Palavras Capturadas</p>
                    <div className="text-xl font-bold text-neutral-900">{clickedWords.size}</div>
                  </div>
                </div>
                <div className="h-8 w-px bg-neutral-200 hidden md:block"></div>
                <div>
                  <p className="text-[10px] font-bold text-neutral-400 uppercase tracking-[0.12em]">Tempo de leitura</p>
                  <div className="text-sm font-semibold text-neutral-600">{estimatedSessionMinutes} min est.</div>
                </div>
              </div>

              <div className="flex flex-wrap items-center gap-3 w-full md:w-auto">
                <button
                  className="flex-1 md:flex-none bg-[#35403A] hover:bg-[#232625] text-white font-semibold px-6 py-2.5 rounded-full text-sm transition-colors flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
                  onClick={() => onPractice && onPractice(sessionWords)}
                  disabled={sessionWords.length === 0}
                >
                  <SparkIcon size={16} />
                  <span>Praticar Capturas</span>
                </button>
                <button
                  className="flex-none border border-neutral-300 rounded-full px-5 py-2.5 text-sm text-neutral-700 hover:bg-neutral-50 transition-colors flex items-center justify-center"
                  onClick={reset}
                >
                  <ReloadIcon size={16} />
                </button>
              </div>
            </div>

            {/* Reading Canvas */}
            <div className="bg-white rounded-xl p-6 md:p-8 lg:p-10 shadow-[0_1px_3px_rgba(20,20,19,0.06)] border border-neutral-200/70 min-h-[500px]">
              <div className="flex gap-4 mb-6 border-b border-neutral-100 pb-4">
                <span className="flex items-center gap-1.5 text-[10px] font-bold text-neutral-400 uppercase tracking-[0.12em]">
                  <span className="w-3 h-3 rounded bg-[#dde2dc] border border-[#CED1C6]"></span>
                  Capturada nesta sessão
                </span>
                <span className="flex items-center gap-1.5 text-[10px] font-bold text-neutral-400 uppercase tracking-[0.12em]">
                  <span className="w-3 h-3 rounded bg-neutral-100 border border-neutral-200"></span>
                  Já salva no banco
                </span>
              </div>

              <div className="text-[18px] leading-[2.2] text-neutral-800 font-ui relative">
                {tokens.length === 0 ? (
                  <div className="flex flex-col items-center justify-center py-20 text-center">
                    <div className="w-16 h-16 bg-neutral-50 rounded-2xl flex items-center justify-center text-neutral-300 mb-4 border border-neutral-100">
                      <SearchIcon size={32} />
                    </div>
                    <h3 className="text-lg font-semibold font-heading text-neutral-900 mb-2">Nada para ler</h3>
                    <p className="text-sm text-neutral-500 leading-relaxed max-w-md">O texto importado não gerou blocos válidos. Tente outro conteúdo.</p>
                  </div>
                ) : tokens.map((token, index) => {
                  if (token.type === 'space') return <span key={index}>{token.raw}</span>;

                  const inBank = bankWords.has(token.clean);
                  const inSession = clickedWords.has(token.clean);
                  const isActive = tooltip?.tokenIdx === index;

                  let bgClass = 'hover:bg-neutral-100 hover:text-neutral-900 rounded cursor-pointer transition-colors';
                  if (inBank) bgClass = 'bg-neutral-100 text-neutral-800 rounded cursor-pointer border border-neutral-200/50 shadow-sm';
                  if (inSession && !inBank) bgClass = 'bg-[#dde2dc] text-[#232625] rounded font-medium cursor-pointer border border-[#CED1C6] shadow-sm';

                  return (
                    <span key={index} className="relative inline-block">
                      <span
                        className={`inline-block px-1 ${bgClass}`}
                        style={{ outline: isActive ? '2px solid #35403A' : 'none', outlineOffset: 1 }}
                        onClick={(event) => {
                          event.stopPropagation();
                          handleWordClick(index, token);
                        }}
                      >
                        {token.raw}
                      </span>

                      {isActive ? (
                        <div className="absolute top-full left-1/2 -translate-x-1/2 mt-3 w-[320px] bg-white rounded-xl shadow-[0_1px_3px_rgba(20,20,19,0.06)] border border-neutral-200/70 z-50 overflow-hidden flex flex-col font-sans" ref={tooltipRef} onClick={(event) => event.stopPropagation()} style={{ boxShadow: '0 8px 24px rgba(53, 64, 58, 0.14)' }}>
                          <div className="bg-neutral-50 border-b border-neutral-100 p-4">
                            <div className="flex items-center gap-2 mb-3">
                              <div className="text-[22px] font-bold text-neutral-900 leading-none">{tooltip.word}</div>
                              <SpeakButton text={tooltip.word} size={14} />
                            </div>
                            <div className="flex gap-2">
                              {tooltip.exist ? (
                                <span className="px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider bg-neutral-200 text-neutral-600 border border-neutral-300/50">Já no banco</span>
                              ) : (
                                <span className="px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider bg-[#dde2dc] text-[#35403A] border border-[#CED1C6]">Novo item</span>
                              )}
                              <span className="px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider border border-neutral-200 text-neutral-500 bg-white">
                                {tooltip.fromAI ? 'IA' : 'Contexto'}
                              </span>
                            </div>
                          </div>

                          <div className="p-4">
                            <div className="text-[10px] font-bold text-neutral-400 uppercase tracking-[0.12em] mb-1.5">Significado contextual</div>
                            {tooltip.loading ? (
                              <div className="flex items-center gap-2 text-sm text-neutral-500 font-medium my-2">
                                <SparkIcon size={14} className="animate-spin text-[#647568]" />
                                Buscando contexto...
                              </div>
                            ) : (
                              <>
                                <div className="text-[15px] font-medium text-neutral-800 mb-3 leading-snug">{tooltip.text}</div>
                                {tooltip.sentence && (
                                  <div className="text-[12px] italic text-neutral-500 bg-neutral-50/80 p-3 rounded-xl border border-neutral-100 leading-relaxed flex items-start gap-2">
                                    <span className="flex-1">{tooltip.sentence}</span>
                                    <SpeakButton text={tooltip.sentence} size={12} className="flex-shrink-0 mt-0.5" />
                                  </div>
                                )}
                              </>
                            )}
                          </div>

                          <div className="p-3 bg-neutral-50 flex border-t border-neutral-100 gap-2">
                            {!tooltip.exist ? (
                              <button className="flex-1 bg-[#35403A] hover:bg-[#232625] text-white font-semibold py-2 rounded-full text-xs transition-colors focus:ring-2 focus:ring-[#35403A]/15 focus:outline-none" onClick={addToBank}>
                                + Salvar palavra
                              </button>
                            ) : sessionWords.find((sw) => sw.wordId === tooltip.existingId) ? (
                              <span className="flex-1 text-center py-2 text-xs font-semibold text-green-600 uppercase tracking-wider inline-flex items-center justify-center gap-1"><CheckCircleIcon size={14} /> Na sess\u00e3o</span>
                            ) : (
                              <button className="flex-1 bg-[#35403A] hover:bg-[#232625] text-white font-semibold py-2 rounded-full text-xs transition-colors" onClick={addToBank}>
                                + Adicionar à prática
                              </button>
                            )}
                            <button className="px-4 border border-neutral-300 hover:bg-neutral-50 text-neutral-700 font-semibold py-2 rounded-full text-xs transition-colors" onClick={() => setTooltip(null)}>
                              Fechar
                            </button>
                          </div>
                        </div>
                      ) : null}
                    </span>
                  );
                })}
              </div>
            </div>

            {/* Captures Footer */}
            {sessionWords.length > 0 ? (
              <div className="bg-white rounded-xl p-6 md:p-8 shadow-[0_1px_3px_rgba(20,20,19,0.06)] border border-neutral-200/70 mb-12">
                <div className="text-[10px] font-bold text-neutral-400 uppercase tracking-[0.12em] mb-4">Capturas dessa leitura</div>
                <div className="flex flex-wrap gap-2">
                  {sessionWords.map((sessionWord) => (
                    <Badge key={sessionWord.wordId} className="bg-[#eef0ec] text-[#35403A] hover:bg-[#dde2dc] border border-[#CED1C6]/50 px-3 py-1 font-bold">
                      {sessionWord.wordText}
                    </Badge>
                  ))}
                </div>
              </div>
            ) : (
              <div className="bg-neutral-50 rounded-xl p-8 border border-neutral-200 border-dashed text-center mb-12">
                <div className="w-12 h-12 bg-white rounded-xl flex items-center justify-center text-neutral-400 mx-auto mb-4 shadow-sm border border-neutral-200">
                  <SearchIcon size={24} />
                </div>
                <h3 className="text-lg font-semibold font-heading text-neutral-900 mb-1">Sem capturas ativas</h3>
                <p className="text-sm text-neutral-500 leading-relaxed max-w-sm mx-auto">Interaja com as palavras acima que você não conhece bem. Elas formarão a base do seu próximo exercício.</p>
              </div>
            )}

          </div>
        )}
      </main>
    </div>
  );
}
