import { createStore } from './main'
import { Task } from '@/types'

export const mockTasks: Task[] = [
  {
    id: 't1',
    title: 'Finalizar Protótipo Mobile',
    status: 'Pendente',
    category: 'Design',
    priority: 'Média',
    deadline: '2024-02-28',
    dateLabel: '28/02',
    iconType: 'clock',
    assignees: [{ initials: 'DK', color: 'bg-[#C2714F]' }],
  },
  {
    id: 't2',
    title: 'Aprovação de Copy - Lançamento',
    status: 'Pendente',
    category: 'Marketing',
    priority: 'Alta',
    deadline: new Date().toISOString(),
    dateLabel: 'HOJE',
    dateColor: 'text-[#C2714F]',
    iconType: 'alert',
    assignees: [{ initials: 'JS', color: 'bg-[#E5B567]' }],
  },
  {
    id: 't3',
    title: 'Integrar API de Pagamento',
    status: 'Pendente',
    category: 'Dev',
    priority: 'Alta',
    deadline: '2024-03-02',
    dateLabel: '02/03',
    iconType: 'clock',
    assignees: [{ initials: 'MK', color: 'bg-[#3D2B1F]' }],
  },
  {
    id: 't4',
    title: 'Setup Pipeline CI/CD',
    status: 'Em Progresso',
    category: 'Infra',
    categoryColor: 'text-[#C2714F]',
    priority: 'Alta',
    deadline: '',
    dateLabel: '65%',
    progress: 65,
    iconType: 'dot',
    assignees: [{ initials: 'DK', color: 'bg-[#C2714F]' }],
  },
  {
    id: 't5',
    title: 'Entrevistas com Usuários',
    status: 'Em Progresso',
    category: 'UX',
    priority: 'Média',
    deadline: '',
    dateLabel: 'Amanhã',
    iconType: 'comment',
    assignees: [
      { initials: 'DK', color: 'bg-[#C2714F]' },
      { initials: 'JS', color: 'bg-[#E5B567]' },
    ],
  },
  {
    id: 't6',
    title: 'Refactor Auth Service',
    status: 'Concluída',
    category: 'Auth',
    priority: 'Média',
    deadline: '2024-02-23',
    dateLabel: '23/02',
    iconType: 'check',
    assignees: [{ initials: 'MK', color: 'bg-[#3D2B1F]' }],
  },
  {
    id: 't7',
    title: 'Fix Navigation Bug (Dashboard)',
    status: 'Concluída',
    category: 'Bug',
    priority: 'Média',
    deadline: '2024-02-24',
    dateLabel: '24/02',
    iconType: 'check',
    assignees: [{ initials: 'DK', color: 'bg-[#C2714F]' }],
  },
]

export default createStore<Task[]>('funilos_tasks', mockTasks)
